apiVersion: v1
kind: Service
metadata:
  name: nothingsbland-app
  namespace: ocean
spec:
  selector:
    app: nothingsbland-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothingsbland-app
  namespace: ocean
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nothingsbland-app
  template:
    metadata:
      labels:
        app: nothingsbland-app
    spec:
      hostname: nothingsbland-app
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea
      containers:    
      - name: nothingsbland-app			# NothingsBland App
        image: nothingsbland-img:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
         requests:
           memory: "100M"      # 100 MB
           cpu: "1m"           # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"      # 100 MB
           cpu: "1m"           # .001 CPU (smallest unit possible)
        volumeMounts:
        - mountPath: /apps/nothingsbland/logs
          name: logs
      volumes:
      - name: logs
        hostPath:
          path: /vault/apps/nothingsbland/logs
          type: DirectoryOrCreate
