apiVersion: v1
kind: Service
metadata:
  name: nothingsbland-nginx
  namespace: ocean
  labels:
    app: nothingsbland-nginx
spec:
  selector:
    app: nothingsbland-nginx
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  externalIPs:
  - 10.0.0.11	  # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothingsbland-nginx
  namespace: ocean
  labels:
    app: nothingsbland-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nothingsbland-nginx
  template:
    metadata:
      labels:
        app: nothingsbland-nginx
    spec:
      hostname: nothingsbland-nginx
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea 	# Only deploy to axe Node    
      containers:
      - name: nothingsbland-nginx     # Nginx Proxy
        image: nothingsbland-nginx:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PROXY_SERVICE_NAME		# Kubernetes Service Discovery?
          value: nothingsbland-app	  # Service DNS Name
        ports:
          - containerPort: 8080 # Nginx
            protocol: TCP
        resources:
         requests:
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU
