apiVersion: v1
kind: Service
metadata:
  name: nginx-nothingsbland
  namespace: dmz
  labels:
    app: nginx-nothingsbland
spec:
  selector:
    app: nginx-nothingsbland
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  externalIPs:
  - 10.0.0.40	# Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nothingsbland
  namespace: dmz
  labels:
    app: nginx-nothingsbland
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nothingsbland
  template:
    metadata:
      labels:
        app: nginx-nothingsbland
    spec:
      hostname: nginx-nothingsbland
      nodeSelector:
        kubernetes.io/hostname: axe.dmz 	# Only deploy to axe Node    
      containers:
      - name: nginx-nothingsbland		# Nginx Proxy
        image: nothingsbland-nginx:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PROXY_SERVICE_NAME		# Kubernetes Service Discovery?
          #value: 10.97.42.169
          value: app-nothingsbland	   	# Service DNS Name
        ports:
          - containerPort: 8080 # Nginx
            protocol: TCP
        resources:
         requests:
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU
