apiVersion: v1
kind: Service
metadata:
  name: axe-haproxy
  namespace: dmz
spec:
  selector:
    app: axe-haproxy
  type: NodePort          
  ports:                  # Everything should rely on internal kubernetes Service DNS resolution
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  externalIPs:
  - 10.0.0.40 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axe-haproxy
  namespace: dmz
  labels:
    app: axe-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axe-haproxy
  template:
    metadata:
      labels:
        app: axe-haproxy
    spec:
      hostname: axe-haproxy
      nodeSelector:
        kubernetes.io/hostname: axe.dmz  # Only deploy to axe Node    
      containers:
      - name: axe-haproxy
        image: haproxy-img:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP            
        resources:
         requests:
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: letsencrypt
      volumes:
      - name: letsencrypt
        hostPath:
          path: /vault/apps/letsencrypt  # directory location on host
          type: DirectoryOrCreate
