apiVersion: v1
kind: Service
metadata:
  name: tiny-plex
  namespace: shawshank
spec:
  selector:
    app: tiny-plex
  ports: 
  - name: plex-tcp-3005
    protocol: TCP
    port: 3005
    targetPort: 3005
  - name: plex-tcp-8324
    protocol: TCP
    port: 8324
    targetPort: 8324
  - name: plex-udp-1900
    protocol: UDP
    port: 1900
    targetPort: 1900
  - name: plex-tcp-32400
    protocol: TCP
    port: 32400
    targetPort: 32400    
  - name: plex-udp-32410
    protocol: UDP
    port: 32410
    targetPort: 32410
  - name: plex-udp-32412
    protocol: UDP
    port: 32412
    targetPort: 32412
  - name: plex-udp-32413
    protocol: UDP
    port: 32413
    targetPort: 32413
  - name: plex-udp-32414
    protocol: UDP
    port: 32414
    targetPort: 32414
  - name: plex-tcp-32469
    protocol: TCP
    port: 32469
    targetPort: 32469    
  externalIPs:
  - 10.0.0.20 # Node IP Address
  - 10.0.0.21
  - 10.0.0.22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-plex
  namespace: shawshank
  labels:
    app: tiny-plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-plex
  template:
    metadata:
      labels:
        app: tiny-plex
    spec:
      hostname: tiny-plex
      nodeSelector:
        kubernetes.io/hostname: tiny.shawshank # Only deploy to Tiny Node
      containers:
      - name: axe-plex
        image: plexinc/pms-docker
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/New_York"
        - name: ADVERTISE_IP
          value: "http://10.0.0.20:32400/"
        # Add Claim
        ports:
        - containerPort: 1900
          protocol: UDP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 32400
          protocol: TCP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        - containerPort: 32469
          protocol: TCP
        resources:
          requests:
            memory: "5140Mi"    # 5140 MB (5 GB)
            cpu: "2000m"        # 2 CPU
          limits:               
            memory: "6168Mi"    # 6168 MB (6 GB)
            cpu: "2500m"        # 2 1/2 CPU
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /transcode
          name: transcode
        - mountPath: /config
          name: config
      volumes:
      - name: data
        hostPath:
          path: /vault/samba/media     # directory location on host
          type: DirectoryOrCreate
      - name: transcode
        hostPath:
          path: /vault/plex/transcode  # directory location on host
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: /vault/plex/config     # directory location on host
          type: DirectoryOrCreate