apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: ocean
spec:
  selector:
    app: pihole
  type: NodePort
  ports: 
  - name: http        # Web Interface
    protocol: TCP
    port: 8080        # Server Port
    targetPort: 80    # Pod Port
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  externalIPs:
  - 10.0.0.10 # black-pearl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: ocean
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostname: pihole
      nodeSelector:
        kubernetes.io/hostname: black-pearl.sea   
      containers:
      - name: pihole
        image: diginc/pi-hole:debian_v3.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/New_York"
        - name: DNS1
          value: 8.8.8.8
        - name: DNS2
          value: 8.8.4.4
        - name: ServerIP
          value: 10.0.0.10 # Node IP Address
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        resources:
          requests:
            memory: "256Mi"     # 256mb
            cpu: "200m"         # 1/5 CPU
          limits:               
            memory: "384Mi"     # 384mb
            cpu: "444m"         # 2.25/5 CPU
