apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: davy-jones-locker.sea # 10.0.0.2
    path: "/Plex"