apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs
  namespace: ocean
spec:
  accessModes:
    - ReadWriteMany
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 6Ti
  storageClassName: plex