# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: plex-nfs
#   namespace: ocean
# spec:
#   capacity:
#     storage: 6Ti
#   #volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain # Don't use Recycle\Delete
#   storageClassName: plex
#   nfs:
#     server: 10.0.0.2
#     path: "/volume2/plex"
  
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-nfs
#   namespace: ocean
# spec:
#   accessModes:
#     - ReadWriteMany
#   #volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 6Ti
#   storageClassName: plex

apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: ocean
spec:
  selector:
    app: plex
  ports: 
  - name: plex-tcp-3005
    protocol: TCP
    port: 3005
    targetPort: 3005
  - name: plex-tcp-8324
    protocol: TCP
    port: 8324
    targetPort: 8324
  - name: plex-udp-1900
    protocol: UDP
    port: 1900
    targetPort: 1900
  - name: plex-tcp-32400
    protocol: TCP
    port: 32400
    targetPort: 32400    
  - name: plex-udp-32410
    protocol: UDP
    port: 32410
    targetPort: 32410
  - name: plex-udp-32412
    protocol: UDP
    port: 32412
    targetPort: 32412
  - name: plex-udp-32413
    protocol: UDP
    port: 32413
    targetPort: 32413
  - name: plex-udp-32414
    protocol: UDP
    port: 32414
    targetPort: 32414
  - name: plex-tcp-32469
    protocol: TCP
    port: 32469
    targetPort: 32469    
  externalIPs:
  - 10.0.0.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: ocean
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostname: flying-dutchman-plex
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea
      containers:
      - name: plex
        image: plexinc/pms-docker:1.14.1.5488-cc260c476
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/New_York"
        - name: ADVERTISE_IP
          value: "http://10.0.0.11:32400/"
        - name: HOSTNAME
          value: "flying-dutchman-plex"
        #- name: ALLOWED_NETWORKS
        #  value: "10.0.0.0/24,172.16.0.0/16"
        # Add Claim
        ports:
        - containerPort: 1900
          protocol: UDP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 32400
          protocol: TCP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        - containerPort: 32469
          protocol: TCP
        resources:
          requests:
            memory: "5140Mi"    # 5140 MB (5 GB)
            cpu: "3000m"        # 3.0 CPU
          limits:               
            memory: "6168Mi"    # 6168 MB (6 GB)
            cpu: "3750m"        # 3.75 CPU
        volumeMounts:
        - name: data
          mountPath: /data
        - name: transcode
          mountPath: /transcode
        - name: config
          mountPath: /config
      volumes:
      - name: data
        hostPath:
          path: /vault-nfs/plex       # directory location on host
          type: DirectoryOrCreate
        # persistentVolumeClaim:
        #   claimName: plex-nfs
      - name: transcode
        hostPath:
          path: /vault/plex/transcode  # directory location on host
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: /vault/plex/config     # directory location on host
          type: DirectoryOrCreate