apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex
spec:
  capacity:
    storage: 6Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Don't use Recycle\Delete
  storageClassName: plex    
  nfs:
    server: davy-jones-locker.sea # 10.0.0.2
    path: "/Plex"