apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-plex
  namespace: ocean
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 6Ti
  storageClassName: plex