apiVersion: v1
kind: Service
metadata:
  name: tiny-samba
  namespace: dmz
spec:
  selector:
    app: tiny-samba
  type: NodePort
  ports: 
  - name: samba-tcp-139
    protocol: TCP
    port: 139
    targetPort: 139
  - name: samba-tcp-445
    protocol: TCP
    port: 445
    targetPort: 445
  externalIPs:
  - 10.0.0.50 # tiny.dmz Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-samba
  namespace: dmz
  labels:
    app: tiny-samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-samba
  template:
    metadata:
      labels:
        app: tiny-samba
    spec:
      hostname: tiny-samba
      nodeSelector:
        kubernetes.io/hostname: tiny.dmz # Only deploy to tiny Node
      containers:
      - name: tiny-samba
        image: dperson/samba
        imagePullPolicy: IfNotPresent
        args: ["-r", "-S", "-s", "media;/media;yes;no;yes;all;none;[];dmz Tiny Media"]
        ports:
        - containerPort: 139
          protocol: TCP
        - containerPort: 445
          protocol: TCP
        resources:
          requests:
            memory: "3084Mi"    # 3084 MB (3 GB)
            cpu: "1000m"         # 1 CPU
          limits:               
            memory: "4096Mi"    # 4096 MB (4 GB)
            cpu: "1500m"        # 1.5 CPU
        volumeMounts:
        - mountPath: /media
          name: media
      volumes:
      - name: media
        hostPath:
          path: /vault/samba/media  # directory location on host
          type: DirectoryOrCreate
