apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: nothingsbland
  name: www
  annotations:
    certmanager.k8s.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  labels:
    app: www
spec:
  rules:
    - host: nothingsbland.com
      http:
        paths:
          - backend:
              serviceName: www
              servicePort: 80
            path: /
    - host: www.nothingsbland.com
      http:
        paths:
          - backend:
              serviceName: www
              servicePort: 80
            path: /
  tls:
    - hosts:
        - nothingsbland.com
        - www.nothingsbland.com
      secretName: nothingsbland-com-tls
---
apiVersion: v1
kind: Service
metadata:
  namespace: nothingsbland
  labels:
    app: www
  name: www
spec:
  selector:
    app: www
  ports:
    - port: 80
      targetPort: http
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: nothingsbland
  name: www
spec:
  secretname: nothingsbland-com-tls
  issuerRef:
    name: letsencrypt
  commonName: nothingsbland.com
  dnsNames:
    - nothingsbland.com
    - www.nothingsbland.com
  acme:
    config:
      - http01:
          ingress: www
        domains:
          - nothingsbland.com
          - www.nothingsbland.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: nothingsbland
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nothingsbland
  name: www
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www   
  template:
    metadata:
      labels:
        app: www
    spec:
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea   
      containers:
        - name: www
          image: black-pearl.sea:5000/nothingsbland-www:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100M"      # 100 MB
              cpu: "1m"           # .001 CPU (smallest unit possible)
            limits:               
              memory: "100M"      # 100 MB
              cpu: "1m"           # .001 CPU (smallest unit possible)
          volumeMounts:
          - name: logs
            mountPath: /apps/nothingsbland/logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs