apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ocean
spec:
  selector:
    app: mongo
  type: NodePort
  ports: 
  - name: mongo-tcp-27017
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: mongo-tcp-27018
    protocol: TCP
    port: 27018
    targetPort: 27018
  - name: mongo-tcp-27019
    protocol: TCP
    port: 27019
    targetPort: 27019        
  externalIPs:
  - 10.0.0.10 # Unassigned Node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ocean
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostname: mongo
      nodeSelector:
        kubernetes.io/hostname: black-pearl.sea # Only deploy to Node (unassigned)
      containers:
      - name: mongo
        image: library/mongo:4.1.10
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: interstellar
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: interstellar
        ports:
        - containerPort: 27017
          protocol: TCP
        - containerPort: 27018
          protocol: TCP
        - containerPort: 27019
          protocol: TCP                    
        resources:
          requests:
            memory: 2048Mi   # 2048 MB (2 GB)
            cpu: 1000m       # 1 CPU
          limits:               
            memory: 2048Mi    # 2048 MB (2 GB)
            cpu: 1500m        # 1.5 CPU
        volumeMounts:
        - mountPath: /data/db
          name: data
      volumes:
      - name: data
        hostPath:
          # Mongo will not start if this is NFS.
          path: /vault/apps/mongo/data  		# host directory
          type: DirectoryOrCreate
