apiVersion: v1
kind: Service
metadata:
  name: juggernaut-mongo
  namespace: shawshank
spec:
  selector:
    app: juggernaut-mongo
  type: NodePort
  ports: 
  - name: mongo-tcp-27017
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: mongo-tcp-27018
    protocol: TCP
    port: 27018
    targetPort: 27018
  - name: mongo-tcp-27019
    protocol: TCP
    port: 27019
    targetPort: 27019        
  externalIPs:
  - 10.0.0.40   # Juggernaut Node IP Address
  # - 10.0.0.41 # Additional NICs not yet supported for Kubernetes
  # - 10.0.0.42 # Additional NICs not yet supported for Kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juggernaut-mongo
  namespace: shawshank
  labels:
    app: juggernaut-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juggernaut-mongo
  template:
    metadata:
      labels:
        app: juggernaut-mongo
    spec:
      hostname: juggernaut-mongo
      nodeSelector:
        kubernetes.io/hostname: juggernaut.shawshank # Only deploy to juggernaut Node
      containers:
      - name: juggernaut-mongo
        image: library/mongo:3.7.9
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: inception
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: inception
        ports:
        - containerPort: 27017
          protocol: TCP
        - containerPort: 27018
          protocol: TCP
        - containerPort: 27019
          protocol: TCP                    
        resources:
          requests:
            memory: 2048Mi   # 2048 MB (2 GB)
            cpu: 2000m       # 2 CPU
          limits:               
            memory: 2048Mi    # 2048 MB (2 GB)
            cpu: 2500m        # 2.5 CPU
        volumeMounts:
        - mountPath: /data/db
          name: data
      volumes:
      - name: data
        hostPath:
          path: /vault/mongo/data  		# host directory
          type: Directory
