apiVersion: v1
kind: Service
metadata:
  name: juggernaut-samba
  namespace: shawshank
spec:
  selector:
    app: juggernaut-samba
  type: NodePort
  ports: 
  - name: samba-tcp-139
    protocol: TCP
    port: 139
    targetPort: 139
  - name: samba-tcp-445
    protocol: TCP
    port: 445
    targetPort: 445
  externalIPs:
  - 10.0.0.40 # Juggernaut Node IP Address
  # - 10.0.0.41
  # - 10.0.0.42
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juggernaut-samba
  namespace: shawshank
  labels:
    app: juggernaut-samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juggernaut-samba
  template:
    metadata:
      labels:
        app: juggernaut-samba
    spec:
      hostname: juggernaut-samba
      nodeSelector:
        kubernetes.io/hostname: juggernaut.shawshank # Only deploy to juggernaut Node
      containers:
      - name: juggernaut-samba
        image: dperson/samba
        imagePullPolicy: IfNotPresent
        args: ["-r", "-S", "-s", "vault;/vault;yes;no;yes;all;none;[];Shawshank Juggernaut Vault"]
        ports:
        - containerPort: 139
          protocol: TCP
        - containerPort: 445
          protocol: TCP
        resources:
          requests:
            memory: "8192Mi"    # 8192 MB (8 GB)
            cpu: "2000m"        # 2 CPU
          limits:               
            memory: "9216Mi"    # 9216 MB (9 GB)
            cpu: "2500m"        # 2.5 CPU
        volumeMounts:
        - mountPath: /vault
          name: vault
      volumes:
      - name: vault
        hostPath:
          path: /vault/samba/vault  # directory location on host
          type: DirectoryOrCreate
