apiVersion: v1
kind: Service
metadata:
  name: shawshank-pihole-service
  namespace: shawshank
spec:
  selector:
    app: shawshank-pihole
  type: NodePort
  ports: 
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  externalIPs:
  - 10.0.0.10 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shawshank-pihole
  namespace: shawshank
  labels:
    app: shawshank-pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shawshank-pihole
  template:
    metadata:
      labels:
        app: shawshank-pihole
    spec:
      nodeSelector:
        kubernetes.io/hostname: warden.shawshank # Only deploy to Warden Node    
      hostname: pihole-shawshank
      hostNetwork: true
      containers:
      - name: shawshank-pihole
        image: diginc/pi-hole:debian_v3.2.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: ""
        - name: DNS1
          value: 8.8.8.8
        - name: DNS2
          value: 8.8.4.4
        - name: ServerIP
          value: 10.0.0.10 # Node IP Address
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        resources:
          requests:
            memory: "256Mi"     # 256mb
            cpu: "200m"         # 1/5 CPU
          limits:               
            memory: "384Mi"     # 384mb
            cpu: "444m"         # 2.25/5 CPU
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole
        - mountPath: /etc/dnsmasq.d
          name: dnsmasq
      volumes:
      - name: pihole
        hostPath:
          path: /apps/pihole/pihole  # directory location on host
          type: Directory
      - name: dnsmasq
        hostPath:
          path: /apps/pihole/dnsmasq.d  # directory location on host
          type: Directory