apiVersion: v1
kind: Service
metadata:
  name: tryhard-pihole-service
  namespace: tryhard
spec:
  selector:
    app: tryhard-pihole
  type: NodePort
  ports: 
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  externalIPs:
  - 172.16.0.10 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tryhard-pihole
  namespace: tryhard
  labels:
    app: tryhard-pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tryhard-pihole
  template:
    metadata:
      labels:
        app: tryhard-pihole
    spec:
      hostname: plex-tryhard
      nodeSelector:
        kubernetes.io/hostname: master-jim.tryhard # Only deploy to Master-Jim   
      containers:
      - name: tryhard-pihole
        image: diginc/pi-hole:debian_v3.2.1
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/New_York"
        - name: DNS1
          value: 8.8.8.8
        - name: DNS2
          value: 8.8.4.4
        - name: ServerIP
          value: 172.16.0.10 # Node IP Address
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        resources:
          requests:
            memory: "256Mi"     # 256mb
            cpu: "200m"         # 1/5 CPU
          limits:               
            memory: "384Mi"     # 384mb
            cpu: "444m"         # 2.25/5 CPU
