apiVersion: v1
kind: Service
metadata:
  name: haproxy-ocean
  namespace: ocean
spec:
  selector:
    app: haproxy-ocean
  type: NodePort          
  ports:                  # Everything should rely on internal kubernetes Service DNS resolution
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  externalIPs:
  - 10.0.0.10 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ocean
  namespace: ocean
  labels:
    app: haproxy-ocean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-ocean
  template:
    metadata:
      labels:
        app: haproxy-ocean
    spec:
      hostname: haproxy-ocean
      nodeSelector:
        kubernetes.io/hostname: black-pearl.sea  # Only deploy to axe Node    
      containers:
      - name: haproxy-ocean
        image: haproxy-img:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP            
        resources:
         requests:
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: letsencrypt
      volumes:
      - name: letsencrypt
        hostPath:
          path: /vault/apps/letsencrypt  # directory location on host
          type: DirectoryOrCreate
