apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: hebron
spec:
  selector:
    app: registry
  ports:
    - name: registry-tcp-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
  externalIPs:
  - 10.0.0.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: hebron
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      hostname: flying-dutchman-registry
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea
      containers:
      - name: registry
        image: hebron-registry:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        ports:
          - containerPort: 5000
            protocol: TCP
        resources:
         requests:
           memory: "500M"      
           cpu: "100m"        
         limits:               
           memory: "500M"      
           cpu: "100m"         
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: registry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  namespace: hebron
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume2/Apps/registry
    server: davy-jones-locker.sea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: hebron
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi  