apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: ocean
spec:
  selector:
    app: registry
  ports:
    - name: registry-tcp-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
  externalIPs:
  - 10.0.0.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: ocean
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      hostname: flying-dutchman-registry
      nodeSelector:
        kubernetes.io/hostname: flying-dutchman.sea
      containers:
      - name: registry
        image: ocean-registry:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        ports:
          - containerPort: 5000
            protocol: TCP
        resources:
         requests:
           memory: "500M"      
           cpu: "100m"        
         limits:               
           memory: "500M"      
           cpu: "100m"         
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
      volumes:
      - name: data
        hostPath:
          path: /vault-nfs/apps/registry       # directory location on host
          type: DirectoryOrCreate