FROM bradjonesllc/docker-haproxy-letsencrypt

ENV CERTS nothingsbland.com
ENV EMAIL brianbland42@gmail.com

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# For testing
ENTRYPOINT ["tail", "-f", "/dev/null"]