apiVersion: v1
kind: Service
metadata:
  name: nothingsbland-nginx-service
  namespace: tryhard
spec:
  selector:
    app: nothingsbland-nginx
  type: NodePort
  ports: 
  - name: http-nginx
    protocol: TCP
    port: 8081
    targetPort: 8081
  externalIPs:
  - 172.16.0.10 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothingsbland-nginx-deployment
  namespace: tryhard
  labels:
    app: nothingsbland-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nothingsbland-nginx
  template:
    metadata:
      labels:
        app: nothingsbland-nginx
    spec:
      hostname: nothingsbland-nginx
      nodeSelector:
        kubernetes.io/hostname: master-jim.tryhard  # Only deploy to master-jim Node    
      containers:
      - name: nothingsbland-nginx	# Nginx Proxy
        image: nginx-img:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_ADDRESS
          value: "10.99.180.71"
        - name: SERVER_PORT
          value: "8081"
        - name: PROXY_PORT
          value: "8080"
        ports:
          - containerPort: 8081 # Nginx
            protocol: TCP
        resources:
         requests:
           memory: "256Mi"     # 256mb
           cpu: "100m"         # .1 CPU
         limits:               
           memory: "256Mi"     # 156mb
           cpu: "100m"         # .1 CPU
