apiVersion: v1
kind: Service
metadata:
  name: nothingsbland-nginx-service
  namespace: tryhard
spec:
  selector:
    app: nothingsbland-nginx
  type: NodePort
  ports: 
  - name: http-nginx      # Remove once HAProxy is online.
    protocol: TCP
    port: 8080
    targetPort: 8080
  externalIPs:
  - 172.16.0.10 # Node IP Address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothingsbland-nginx-deployment
  namespace: tryhard
  labels:
    app: nothingsbland-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nothingsbland-nginx
  template:
    metadata:
      labels:
        app: nothingsbland-nginx
    spec:
      hostname: nothingsbland-nginx
      nodeSelector:
        kubernetes.io/hostname: master-jim.tryhard  # Only deploy to master-jim Node    
      containers:
      - name: nothingsbland-nginx	# Nginx Proxy
        image: nginx-img:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_ADDRESS
          value: "10.99.180.71" # How to dynamically get Service IP? Manual intervention required here (for now)
        - name: SERVER_PORT
          value: "8080"         # Testing Port Mirror on Kubernetes
        - name: PROXY_PORT
          value: "8080"         # Testing Port Mirror on Kubernetes
        ports:
          - containerPort: 8080 # Nginx
            protocol: TCP
        resources:
         requests:
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU (smallest unit possible)
         limits:               
           memory: "100M"       # 100 MB
           cpu: "1m"            # .001 CPU
